//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myphones.ServerMgmt
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://myphones.com/webservices/", ConfigurationName="Myphones.ServerMgmt.MyPhonesServersSoap")]
    public interface MyPhonesServersSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myphones.com/webservices/GetIfUsageStats", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string[]> GetIfUsageStatsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myphones.com/webservices/GetRemoteProvisionEndpoints", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.GetRemoteProvisionEndpointsResponse> GetRemoteProvisionEndpointsAsync(Myphones.ServerMgmt.GetRemoteProvisionEndpointsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myphones.com/webservices/GetNewPhonePictures", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.GetNewPhonePicturesResponse> GetNewPhonePicturesAsync(Myphones.ServerMgmt.GetNewPhonePicturesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myphones.com/webservices/GetServerConfigDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.GetServerConfigDetailsResponse> GetServerConfigDetailsAsync(Myphones.ServerMgmt.GetServerConfigDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myphones.com/webservices/SetGlobalConfig", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.SetGlobalConfigResponse> SetGlobalConfigAsync(Myphones.ServerMgmt.SetGlobalConfigRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myphones.com/webservices/GetDialPlanDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.GetDialPlanDetailsResponse> GetDialPlanDetailsAsync(Myphones.ServerMgmt.GetDialPlanDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myphones.com/webservices/SetDialPlan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.SetDialPlanResponse> SetDialPlanAsync(Myphones.ServerMgmt.SetDialPlanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myphones.com/webservices/PublishDialPlan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.PublishDialPlanResponse> PublishDialPlanAsync(Myphones.ServerMgmt.PublishDialPlanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myphones.com/webservices/GetTrunkRoutes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.GetTrunkRoutesResponse> GetTrunkRoutesAsync(Myphones.ServerMgmt.GetTrunkRoutesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myphones.com/webservices/SetTrunkRoutes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.SetTrunkRoutesResponse> SetTrunkRoutesAsync(Myphones.ServerMgmt.SetTrunkRoutesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myphones.com/webservices/PublishTrunkRoutes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.PublishTrunkRoutesResponse> PublishTrunkRoutesAsync(Myphones.ServerMgmt.PublishTrunkRoutesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myphones.com/webservices/ResetCache", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.ResetCacheResponse> ResetCacheAsync(Myphones.ServerMgmt.ResetCacheRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myphones.com/webservices/ReloadContentServerCache", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.ReloadContentServerCacheResponse> ReloadContentServerCacheAsync(Myphones.ServerMgmt.ReloadContentServerCacheRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myphones.com/webservices/GetMemcachedClientStats", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.GetMemcachedClientStatsResponse> GetMemcachedClientStatsAsync(Myphones.ServerMgmt.GetMemcachedClientStatsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myphones.com/webservices/GetMemcachedServerStats", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.GetMemcachedServerStatsResponse> GetMemcachedServerStatsAsync(Myphones.ServerMgmt.GetMemcachedServerStatsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myphones.com/webservices/GetMemcachedValues", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.GetMemcachedValuesResponse> GetMemcachedValuesAsync(Myphones.ServerMgmt.GetMemcachedValuesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myphones.com/webservices/ResetMemcachedTree", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.ResetMemcachedTreeResponse> ResetMemcachedTreeAsync(Myphones.ServerMgmt.ResetMemcachedTreeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myphones.com/webservices/ResetApplianceMemcachedTree", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.ResetApplianceMemcachedTreeResponse> ResetApplianceMemcachedTreeAsync(Myphones.ServerMgmt.ResetApplianceMemcachedTreeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myphones.com/webservices/ResetMemcachedKeyname", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.ResetMemcachedKeynameResponse> ResetMemcachedKeynameAsync(Myphones.ServerMgmt.ResetMemcachedKeynameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myphones.com/webservices/GetDBConnInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.GetDBConnInfoResponse> GetDBConnInfoAsync(Myphones.ServerMgmt.GetDBConnInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myphones.com/webservices/ResetDBConns", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.ResetDBConnsResponse> ResetDBConnsAsync(Myphones.ServerMgmt.ResetDBConnsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myphones.com/webservices/SetDisplayDBConnInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.SetDisplayDBConnInfoResponse> SetDisplayDBConnInfoAsync(Myphones.ServerMgmt.SetDisplayDBConnInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myphones.com/webservices/SetServerRunnableState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.SetServerRunnableStateResponse> SetServerRunnableStateAsync(Myphones.ServerMgmt.SetServerRunnableStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myphones.com/webservices/SetServerDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.SetServerDetailsResponse> SetServerDetailsAsync(Myphones.ServerMgmt.SetServerDetailsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://myphones.com/webservices/")]
    public partial class RemoteClientInfoHeader
    {
        
        private string ipAddressField;
        
        private string userAgentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ipAddress
        {
            get
            {
                return this.ipAddressField;
            }
            set
            {
                this.ipAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string userAgent
        {
            get
            {
                return this.userAgentField;
            }
            set
            {
                this.userAgentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://myphones.com/webservices/")]
    public partial class SoftswitchMonitorPhonePicture
    {
        
        private string phoneNameField;
        
        private byte[] phonePictureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string phoneName
        {
            get
            {
                return this.phoneNameField;
            }
            set
            {
                this.phoneNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] phonePicture
        {
            get
            {
                return this.phonePictureField;
            }
            set
            {
                this.phonePictureField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRemoteProvisionEndpoints", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class GetRemoteProvisionEndpointsRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://myphones.com/webservices/")]
        public Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=0)]
        public string sessionToken;
        
        public GetRemoteProvisionEndpointsRequest()
        {
        }
        
        public GetRemoteProvisionEndpointsRequest(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRemoteProvisionEndpointsResponse", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class GetRemoteProvisionEndpointsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=0)]
        public string[] GetRemoteProvisionEndpointsResult;
        
        public GetRemoteProvisionEndpointsResponse()
        {
        }
        
        public GetRemoteProvisionEndpointsResponse(string[] GetRemoteProvisionEndpointsResult)
        {
            this.GetRemoteProvisionEndpointsResult = GetRemoteProvisionEndpointsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNewPhonePictures", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class GetNewPhonePicturesRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://myphones.com/webservices/")]
        public Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=0)]
        public string sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=1)]
        public string[] existingPhoneNames;
        
        public GetNewPhonePicturesRequest()
        {
        }
        
        public GetNewPhonePicturesRequest(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string[] existingPhoneNames)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
            this.existingPhoneNames = existingPhoneNames;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNewPhonePicturesResponse", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class GetNewPhonePicturesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=0)]
        public Myphones.ServerMgmt.SoftswitchMonitorPhonePicture[] GetNewPhonePicturesResult;
        
        public GetNewPhonePicturesResponse()
        {
        }
        
        public GetNewPhonePicturesResponse(Myphones.ServerMgmt.SoftswitchMonitorPhonePicture[] GetNewPhonePicturesResult)
        {
            this.GetNewPhonePicturesResult = GetNewPhonePicturesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServerConfigDetails", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class GetServerConfigDetailsRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://myphones.com/webservices/")]
        public Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=0)]
        public string sessionToken;
        
        public GetServerConfigDetailsRequest()
        {
        }
        
        public GetServerConfigDetailsRequest(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServerConfigDetailsResponse", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class GetServerConfigDetailsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=0)]
        public string GetServerConfigDetailsResult;
        
        public GetServerConfigDetailsResponse()
        {
        }
        
        public GetServerConfigDetailsResponse(string GetServerConfigDetailsResult)
        {
            this.GetServerConfigDetailsResult = GetServerConfigDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetGlobalConfig", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class SetGlobalConfigRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://myphones.com/webservices/")]
        public Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=0)]
        public string sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=1)]
        public string globalConfigXml;
        
        public SetGlobalConfigRequest()
        {
        }
        
        public SetGlobalConfigRequest(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string globalConfigXml)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
            this.globalConfigXml = globalConfigXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetGlobalConfigResponse", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class SetGlobalConfigResponse
    {
        
        public SetGlobalConfigResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDialPlanDetails", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class GetDialPlanDetailsRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://myphones.com/webservices/")]
        public Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=0)]
        public string sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=1)]
        public string planName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=2)]
        public int filterByID;
        
        public GetDialPlanDetailsRequest()
        {
        }
        
        public GetDialPlanDetailsRequest(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string planName, int filterByID)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
            this.planName = planName;
            this.filterByID = filterByID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDialPlanDetailsResponse", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class GetDialPlanDetailsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=0)]
        public string GetDialPlanDetailsResult;
        
        public GetDialPlanDetailsResponse()
        {
        }
        
        public GetDialPlanDetailsResponse(string GetDialPlanDetailsResult)
        {
            this.GetDialPlanDetailsResult = GetDialPlanDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetDialPlan", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class SetDialPlanRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://myphones.com/webservices/")]
        public Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=0)]
        public string sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=1)]
        public string dialPlanName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=2)]
        public string filterKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=3)]
        public string dialPlanXml;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=4)]
        public bool isSubscriberEntry;
        
        public SetDialPlanRequest()
        {
        }
        
        public SetDialPlanRequest(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string dialPlanName, string filterKey, string dialPlanXml, bool isSubscriberEntry)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
            this.dialPlanName = dialPlanName;
            this.filterKey = filterKey;
            this.dialPlanXml = dialPlanXml;
            this.isSubscriberEntry = isSubscriberEntry;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetDialPlanResponse", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class SetDialPlanResponse
    {
        
        public SetDialPlanResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PublishDialPlan", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class PublishDialPlanRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://myphones.com/webservices/")]
        public Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=0)]
        public string sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=1)]
        public string dialPlanName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=2)]
        public string filterKey;
        
        public PublishDialPlanRequest()
        {
        }
        
        public PublishDialPlanRequest(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string dialPlanName, string filterKey)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
            this.dialPlanName = dialPlanName;
            this.filterKey = filterKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PublishDialPlanResponse", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class PublishDialPlanResponse
    {
        
        public PublishDialPlanResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTrunkRoutes", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class GetTrunkRoutesRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://myphones.com/webservices/")]
        public Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=0)]
        public string sessionToken;
        
        public GetTrunkRoutesRequest()
        {
        }
        
        public GetTrunkRoutesRequest(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTrunkRoutesResponse", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class GetTrunkRoutesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=0)]
        public string GetTrunkRoutesResult;
        
        public GetTrunkRoutesResponse()
        {
        }
        
        public GetTrunkRoutesResponse(string GetTrunkRoutesResult)
        {
            this.GetTrunkRoutesResult = GetTrunkRoutesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetTrunkRoutes", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class SetTrunkRoutesRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://myphones.com/webservices/")]
        public Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=0)]
        public string sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=1)]
        public string trunkRoutesXml;
        
        public SetTrunkRoutesRequest()
        {
        }
        
        public SetTrunkRoutesRequest(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string trunkRoutesXml)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
            this.trunkRoutesXml = trunkRoutesXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetTrunkRoutesResponse", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class SetTrunkRoutesResponse
    {
        
        public SetTrunkRoutesResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PublishTrunkRoutes", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class PublishTrunkRoutesRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://myphones.com/webservices/")]
        public Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=0)]
        public string sessionToken;
        
        public PublishTrunkRoutesRequest()
        {
        }
        
        public PublishTrunkRoutesRequest(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PublishTrunkRoutesResponse", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class PublishTrunkRoutesResponse
    {
        
        public PublishTrunkRoutesResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResetCache", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class ResetCacheRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://myphones.com/webservices/")]
        public Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=0)]
        public string sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=1)]
        public int[] softswitchServerIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=2)]
        public string[] resetContexts;
        
        public ResetCacheRequest()
        {
        }
        
        public ResetCacheRequest(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, int[] softswitchServerIds, string[] resetContexts)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
            this.softswitchServerIds = softswitchServerIds;
            this.resetContexts = resetContexts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResetCacheResponse", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class ResetCacheResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=0)]
        public string ResetCacheResult;
        
        public ResetCacheResponse()
        {
        }
        
        public ResetCacheResponse(string ResetCacheResult)
        {
            this.ResetCacheResult = ResetCacheResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReloadContentServerCache", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class ReloadContentServerCacheRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://myphones.com/webservices/")]
        public Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=0)]
        public string sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=1)]
        public int[] softswitchServerIds;
        
        public ReloadContentServerCacheRequest()
        {
        }
        
        public ReloadContentServerCacheRequest(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, int[] softswitchServerIds)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
            this.softswitchServerIds = softswitchServerIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReloadContentServerCacheResponse", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class ReloadContentServerCacheResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=0)]
        public string ReloadContentServerCacheResult;
        
        public ReloadContentServerCacheResponse()
        {
        }
        
        public ReloadContentServerCacheResponse(string ReloadContentServerCacheResult)
        {
            this.ReloadContentServerCacheResult = ReloadContentServerCacheResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMemcachedClientStats", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class GetMemcachedClientStatsRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://myphones.com/webservices/")]
        public Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=0)]
        public string sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=1)]
        public string cacheName;
        
        public GetMemcachedClientStatsRequest()
        {
        }
        
        public GetMemcachedClientStatsRequest(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string cacheName)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
            this.cacheName = cacheName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMemcachedClientStatsResponse", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class GetMemcachedClientStatsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=0)]
        public string GetMemcachedClientStatsResult;
        
        public GetMemcachedClientStatsResponse()
        {
        }
        
        public GetMemcachedClientStatsResponse(string GetMemcachedClientStatsResult)
        {
            this.GetMemcachedClientStatsResult = GetMemcachedClientStatsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMemcachedServerStats", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class GetMemcachedServerStatsRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://myphones.com/webservices/")]
        public Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=0)]
        public string sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=1)]
        public int[] serverIds;
        
        public GetMemcachedServerStatsRequest()
        {
        }
        
        public GetMemcachedServerStatsRequest(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, int[] serverIds)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
            this.serverIds = serverIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMemcachedServerStatsResponse", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class GetMemcachedServerStatsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=0)]
        public string GetMemcachedServerStatsResult;
        
        public GetMemcachedServerStatsResponse()
        {
        }
        
        public GetMemcachedServerStatsResponse(string GetMemcachedServerStatsResult)
        {
            this.GetMemcachedServerStatsResult = GetMemcachedServerStatsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMemcachedValues", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class GetMemcachedValuesRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://myphones.com/webservices/")]
        public Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=0)]
        public string sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=1)]
        public string cacheName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=2)]
        public string[] keyNames;
        
        public GetMemcachedValuesRequest()
        {
        }
        
        public GetMemcachedValuesRequest(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string cacheName, string[] keyNames)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
            this.cacheName = cacheName;
            this.keyNames = keyNames;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMemcachedValuesResponse", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class GetMemcachedValuesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=0)]
        public string[] GetMemcachedValuesResult;
        
        public GetMemcachedValuesResponse()
        {
        }
        
        public GetMemcachedValuesResponse(string[] GetMemcachedValuesResult)
        {
            this.GetMemcachedValuesResult = GetMemcachedValuesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResetMemcachedTree", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class ResetMemcachedTreeRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://myphones.com/webservices/")]
        public Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=0)]
        public string sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=1)]
        public string cacheName;
        
        public ResetMemcachedTreeRequest()
        {
        }
        
        public ResetMemcachedTreeRequest(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string cacheName)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
            this.cacheName = cacheName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResetMemcachedTreeResponse", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class ResetMemcachedTreeResponse
    {
        
        public ResetMemcachedTreeResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResetApplianceMemcachedTree", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class ResetApplianceMemcachedTreeRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://myphones.com/webservices/")]
        public Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=0)]
        public string sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=1)]
        public string[] applianceNames;
        
        public ResetApplianceMemcachedTreeRequest()
        {
        }
        
        public ResetApplianceMemcachedTreeRequest(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string[] applianceNames)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
            this.applianceNames = applianceNames;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResetApplianceMemcachedTreeResponse", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class ResetApplianceMemcachedTreeResponse
    {
        
        public ResetApplianceMemcachedTreeResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResetMemcachedKeyname", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class ResetMemcachedKeynameRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://myphones.com/webservices/")]
        public Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=0)]
        public string sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=1)]
        public string cacheName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=2)]
        public string[] keyNames;
        
        public ResetMemcachedKeynameRequest()
        {
        }
        
        public ResetMemcachedKeynameRequest(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string cacheName, string[] keyNames)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
            this.cacheName = cacheName;
            this.keyNames = keyNames;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResetMemcachedKeynameResponse", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class ResetMemcachedKeynameResponse
    {
        
        public ResetMemcachedKeynameResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDBConnInfo", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class GetDBConnInfoRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://myphones.com/webservices/")]
        public Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=0)]
        public string sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=1)]
        public int[] softswitchServerIds;
        
        public GetDBConnInfoRequest()
        {
        }
        
        public GetDBConnInfoRequest(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, int[] softswitchServerIds)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
            this.softswitchServerIds = softswitchServerIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDBConnInfoResponse", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class GetDBConnInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=0)]
        public string GetDBConnInfoResult;
        
        public GetDBConnInfoResponse()
        {
        }
        
        public GetDBConnInfoResponse(string GetDBConnInfoResult)
        {
            this.GetDBConnInfoResult = GetDBConnInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResetDBConns", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class ResetDBConnsRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://myphones.com/webservices/")]
        public Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=0)]
        public string sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=1)]
        public int[] softswitchServerIds;
        
        public ResetDBConnsRequest()
        {
        }
        
        public ResetDBConnsRequest(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, int[] softswitchServerIds)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
            this.softswitchServerIds = softswitchServerIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResetDBConnsResponse", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class ResetDBConnsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=0)]
        public string ResetDBConnsResult;
        
        public ResetDBConnsResponse()
        {
        }
        
        public ResetDBConnsResponse(string ResetDBConnsResult)
        {
            this.ResetDBConnsResult = ResetDBConnsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetDisplayDBConnInfo", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class SetDisplayDBConnInfoRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://myphones.com/webservices/")]
        public Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=0)]
        public string sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=1)]
        public int[] softswitchServerIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=2)]
        public bool displayOn;
        
        public SetDisplayDBConnInfoRequest()
        {
        }
        
        public SetDisplayDBConnInfoRequest(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, int[] softswitchServerIds, bool displayOn)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
            this.softswitchServerIds = softswitchServerIds;
            this.displayOn = displayOn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetDisplayDBConnInfoResponse", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class SetDisplayDBConnInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=0)]
        public string SetDisplayDBConnInfoResult;
        
        public SetDisplayDBConnInfoResponse()
        {
        }
        
        public SetDisplayDBConnInfoResponse(string SetDisplayDBConnInfoResult)
        {
            this.SetDisplayDBConnInfoResult = SetDisplayDBConnInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetServerRunnableState", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class SetServerRunnableStateRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://myphones.com/webservices/")]
        public Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=0)]
        public string sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=1)]
        public int[] softswitchServerIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=2)]
        public bool[] states;
        
        public SetServerRunnableStateRequest()
        {
        }
        
        public SetServerRunnableStateRequest(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, int[] softswitchServerIds, bool[] states)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
            this.softswitchServerIds = softswitchServerIds;
            this.states = states;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetServerRunnableStateResponse", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class SetServerRunnableStateResponse
    {
        
        public SetServerRunnableStateResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetServerDetails", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class SetServerDetailsRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://myphones.com/webservices/")]
        public Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=0)]
        public string sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=1)]
        public int[] softswitchServerIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=2)]
        public int[] runnables;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=3)]
        public string[] details;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=4)]
        public int[] weightedLoads;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://myphones.com/webservices/", Order=5)]
        public bool reevalRunnable;
        
        public SetServerDetailsRequest()
        {
        }
        
        public SetServerDetailsRequest(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, int[] softswitchServerIds, int[] runnables, string[] details, int[] weightedLoads, bool reevalRunnable)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
            this.softswitchServerIds = softswitchServerIds;
            this.runnables = runnables;
            this.details = details;
            this.weightedLoads = weightedLoads;
            this.reevalRunnable = reevalRunnable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetServerDetailsResponse", WrapperNamespace="http://myphones.com/webservices/", IsWrapped=true)]
    public partial class SetServerDetailsResponse
    {
        
        public SetServerDetailsResponse()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    public interface MyPhonesServersSoapChannel : Myphones.ServerMgmt.MyPhonesServersSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    public partial class MyPhonesServersSoapClient : System.ServiceModel.ClientBase<Myphones.ServerMgmt.MyPhonesServersSoap>, Myphones.ServerMgmt.MyPhonesServersSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MyPhonesServersSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(MyPhonesServersSoapClient.GetBindingForEndpoint(endpointConfiguration), MyPhonesServersSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MyPhonesServersSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MyPhonesServersSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MyPhonesServersSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MyPhonesServersSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MyPhonesServersSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string[]> GetIfUsageStatsAsync()
        {
            return base.Channel.GetIfUsageStatsAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.GetRemoteProvisionEndpointsResponse> Myphones.ServerMgmt.MyPhonesServersSoap.GetRemoteProvisionEndpointsAsync(Myphones.ServerMgmt.GetRemoteProvisionEndpointsRequest request)
        {
            return base.Channel.GetRemoteProvisionEndpointsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.ServerMgmt.GetRemoteProvisionEndpointsResponse> GetRemoteProvisionEndpointsAsync(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken)
        {
            Myphones.ServerMgmt.GetRemoteProvisionEndpointsRequest inValue = new Myphones.ServerMgmt.GetRemoteProvisionEndpointsRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            return ((Myphones.ServerMgmt.MyPhonesServersSoap)(this)).GetRemoteProvisionEndpointsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.GetNewPhonePicturesResponse> Myphones.ServerMgmt.MyPhonesServersSoap.GetNewPhonePicturesAsync(Myphones.ServerMgmt.GetNewPhonePicturesRequest request)
        {
            return base.Channel.GetNewPhonePicturesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.ServerMgmt.GetNewPhonePicturesResponse> GetNewPhonePicturesAsync(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string[] existingPhoneNames)
        {
            Myphones.ServerMgmt.GetNewPhonePicturesRequest inValue = new Myphones.ServerMgmt.GetNewPhonePicturesRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            inValue.existingPhoneNames = existingPhoneNames;
            return ((Myphones.ServerMgmt.MyPhonesServersSoap)(this)).GetNewPhonePicturesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.GetServerConfigDetailsResponse> Myphones.ServerMgmt.MyPhonesServersSoap.GetServerConfigDetailsAsync(Myphones.ServerMgmt.GetServerConfigDetailsRequest request)
        {
            return base.Channel.GetServerConfigDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.ServerMgmt.GetServerConfigDetailsResponse> GetServerConfigDetailsAsync(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken)
        {
            Myphones.ServerMgmt.GetServerConfigDetailsRequest inValue = new Myphones.ServerMgmt.GetServerConfigDetailsRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            return ((Myphones.ServerMgmt.MyPhonesServersSoap)(this)).GetServerConfigDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.SetGlobalConfigResponse> Myphones.ServerMgmt.MyPhonesServersSoap.SetGlobalConfigAsync(Myphones.ServerMgmt.SetGlobalConfigRequest request)
        {
            return base.Channel.SetGlobalConfigAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.ServerMgmt.SetGlobalConfigResponse> SetGlobalConfigAsync(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string globalConfigXml)
        {
            Myphones.ServerMgmt.SetGlobalConfigRequest inValue = new Myphones.ServerMgmt.SetGlobalConfigRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            inValue.globalConfigXml = globalConfigXml;
            return ((Myphones.ServerMgmt.MyPhonesServersSoap)(this)).SetGlobalConfigAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.GetDialPlanDetailsResponse> Myphones.ServerMgmt.MyPhonesServersSoap.GetDialPlanDetailsAsync(Myphones.ServerMgmt.GetDialPlanDetailsRequest request)
        {
            return base.Channel.GetDialPlanDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.ServerMgmt.GetDialPlanDetailsResponse> GetDialPlanDetailsAsync(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string planName, int filterByID)
        {
            Myphones.ServerMgmt.GetDialPlanDetailsRequest inValue = new Myphones.ServerMgmt.GetDialPlanDetailsRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            inValue.planName = planName;
            inValue.filterByID = filterByID;
            return ((Myphones.ServerMgmt.MyPhonesServersSoap)(this)).GetDialPlanDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.SetDialPlanResponse> Myphones.ServerMgmt.MyPhonesServersSoap.SetDialPlanAsync(Myphones.ServerMgmt.SetDialPlanRequest request)
        {
            return base.Channel.SetDialPlanAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.ServerMgmt.SetDialPlanResponse> SetDialPlanAsync(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string dialPlanName, string filterKey, string dialPlanXml, bool isSubscriberEntry)
        {
            Myphones.ServerMgmt.SetDialPlanRequest inValue = new Myphones.ServerMgmt.SetDialPlanRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            inValue.dialPlanName = dialPlanName;
            inValue.filterKey = filterKey;
            inValue.dialPlanXml = dialPlanXml;
            inValue.isSubscriberEntry = isSubscriberEntry;
            return ((Myphones.ServerMgmt.MyPhonesServersSoap)(this)).SetDialPlanAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.PublishDialPlanResponse> Myphones.ServerMgmt.MyPhonesServersSoap.PublishDialPlanAsync(Myphones.ServerMgmt.PublishDialPlanRequest request)
        {
            return base.Channel.PublishDialPlanAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.ServerMgmt.PublishDialPlanResponse> PublishDialPlanAsync(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string dialPlanName, string filterKey)
        {
            Myphones.ServerMgmt.PublishDialPlanRequest inValue = new Myphones.ServerMgmt.PublishDialPlanRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            inValue.dialPlanName = dialPlanName;
            inValue.filterKey = filterKey;
            return ((Myphones.ServerMgmt.MyPhonesServersSoap)(this)).PublishDialPlanAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.GetTrunkRoutesResponse> Myphones.ServerMgmt.MyPhonesServersSoap.GetTrunkRoutesAsync(Myphones.ServerMgmt.GetTrunkRoutesRequest request)
        {
            return base.Channel.GetTrunkRoutesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.ServerMgmt.GetTrunkRoutesResponse> GetTrunkRoutesAsync(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken)
        {
            Myphones.ServerMgmt.GetTrunkRoutesRequest inValue = new Myphones.ServerMgmt.GetTrunkRoutesRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            return ((Myphones.ServerMgmt.MyPhonesServersSoap)(this)).GetTrunkRoutesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.SetTrunkRoutesResponse> Myphones.ServerMgmt.MyPhonesServersSoap.SetTrunkRoutesAsync(Myphones.ServerMgmt.SetTrunkRoutesRequest request)
        {
            return base.Channel.SetTrunkRoutesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.ServerMgmt.SetTrunkRoutesResponse> SetTrunkRoutesAsync(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string trunkRoutesXml)
        {
            Myphones.ServerMgmt.SetTrunkRoutesRequest inValue = new Myphones.ServerMgmt.SetTrunkRoutesRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            inValue.trunkRoutesXml = trunkRoutesXml;
            return ((Myphones.ServerMgmt.MyPhonesServersSoap)(this)).SetTrunkRoutesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.PublishTrunkRoutesResponse> Myphones.ServerMgmt.MyPhonesServersSoap.PublishTrunkRoutesAsync(Myphones.ServerMgmt.PublishTrunkRoutesRequest request)
        {
            return base.Channel.PublishTrunkRoutesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.ServerMgmt.PublishTrunkRoutesResponse> PublishTrunkRoutesAsync(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken)
        {
            Myphones.ServerMgmt.PublishTrunkRoutesRequest inValue = new Myphones.ServerMgmt.PublishTrunkRoutesRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            return ((Myphones.ServerMgmt.MyPhonesServersSoap)(this)).PublishTrunkRoutesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.ResetCacheResponse> Myphones.ServerMgmt.MyPhonesServersSoap.ResetCacheAsync(Myphones.ServerMgmt.ResetCacheRequest request)
        {
            return base.Channel.ResetCacheAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.ServerMgmt.ResetCacheResponse> ResetCacheAsync(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, int[] softswitchServerIds, string[] resetContexts)
        {
            Myphones.ServerMgmt.ResetCacheRequest inValue = new Myphones.ServerMgmt.ResetCacheRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            inValue.softswitchServerIds = softswitchServerIds;
            inValue.resetContexts = resetContexts;
            return ((Myphones.ServerMgmt.MyPhonesServersSoap)(this)).ResetCacheAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.ReloadContentServerCacheResponse> Myphones.ServerMgmt.MyPhonesServersSoap.ReloadContentServerCacheAsync(Myphones.ServerMgmt.ReloadContentServerCacheRequest request)
        {
            return base.Channel.ReloadContentServerCacheAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.ServerMgmt.ReloadContentServerCacheResponse> ReloadContentServerCacheAsync(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, int[] softswitchServerIds)
        {
            Myphones.ServerMgmt.ReloadContentServerCacheRequest inValue = new Myphones.ServerMgmt.ReloadContentServerCacheRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            inValue.softswitchServerIds = softswitchServerIds;
            return ((Myphones.ServerMgmt.MyPhonesServersSoap)(this)).ReloadContentServerCacheAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.GetMemcachedClientStatsResponse> Myphones.ServerMgmt.MyPhonesServersSoap.GetMemcachedClientStatsAsync(Myphones.ServerMgmt.GetMemcachedClientStatsRequest request)
        {
            return base.Channel.GetMemcachedClientStatsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.ServerMgmt.GetMemcachedClientStatsResponse> GetMemcachedClientStatsAsync(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string cacheName)
        {
            Myphones.ServerMgmt.GetMemcachedClientStatsRequest inValue = new Myphones.ServerMgmt.GetMemcachedClientStatsRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            inValue.cacheName = cacheName;
            return ((Myphones.ServerMgmt.MyPhonesServersSoap)(this)).GetMemcachedClientStatsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.GetMemcachedServerStatsResponse> Myphones.ServerMgmt.MyPhonesServersSoap.GetMemcachedServerStatsAsync(Myphones.ServerMgmt.GetMemcachedServerStatsRequest request)
        {
            return base.Channel.GetMemcachedServerStatsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.ServerMgmt.GetMemcachedServerStatsResponse> GetMemcachedServerStatsAsync(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, int[] serverIds)
        {
            Myphones.ServerMgmt.GetMemcachedServerStatsRequest inValue = new Myphones.ServerMgmt.GetMemcachedServerStatsRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            inValue.serverIds = serverIds;
            return ((Myphones.ServerMgmt.MyPhonesServersSoap)(this)).GetMemcachedServerStatsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.GetMemcachedValuesResponse> Myphones.ServerMgmt.MyPhonesServersSoap.GetMemcachedValuesAsync(Myphones.ServerMgmt.GetMemcachedValuesRequest request)
        {
            return base.Channel.GetMemcachedValuesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.ServerMgmt.GetMemcachedValuesResponse> GetMemcachedValuesAsync(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string cacheName, string[] keyNames)
        {
            Myphones.ServerMgmt.GetMemcachedValuesRequest inValue = new Myphones.ServerMgmt.GetMemcachedValuesRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            inValue.cacheName = cacheName;
            inValue.keyNames = keyNames;
            return ((Myphones.ServerMgmt.MyPhonesServersSoap)(this)).GetMemcachedValuesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.ResetMemcachedTreeResponse> Myphones.ServerMgmt.MyPhonesServersSoap.ResetMemcachedTreeAsync(Myphones.ServerMgmt.ResetMemcachedTreeRequest request)
        {
            return base.Channel.ResetMemcachedTreeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.ServerMgmt.ResetMemcachedTreeResponse> ResetMemcachedTreeAsync(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string cacheName)
        {
            Myphones.ServerMgmt.ResetMemcachedTreeRequest inValue = new Myphones.ServerMgmt.ResetMemcachedTreeRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            inValue.cacheName = cacheName;
            return ((Myphones.ServerMgmt.MyPhonesServersSoap)(this)).ResetMemcachedTreeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.ResetApplianceMemcachedTreeResponse> Myphones.ServerMgmt.MyPhonesServersSoap.ResetApplianceMemcachedTreeAsync(Myphones.ServerMgmt.ResetApplianceMemcachedTreeRequest request)
        {
            return base.Channel.ResetApplianceMemcachedTreeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.ServerMgmt.ResetApplianceMemcachedTreeResponse> ResetApplianceMemcachedTreeAsync(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string[] applianceNames)
        {
            Myphones.ServerMgmt.ResetApplianceMemcachedTreeRequest inValue = new Myphones.ServerMgmt.ResetApplianceMemcachedTreeRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            inValue.applianceNames = applianceNames;
            return ((Myphones.ServerMgmt.MyPhonesServersSoap)(this)).ResetApplianceMemcachedTreeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.ResetMemcachedKeynameResponse> Myphones.ServerMgmt.MyPhonesServersSoap.ResetMemcachedKeynameAsync(Myphones.ServerMgmt.ResetMemcachedKeynameRequest request)
        {
            return base.Channel.ResetMemcachedKeynameAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.ServerMgmt.ResetMemcachedKeynameResponse> ResetMemcachedKeynameAsync(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string cacheName, string[] keyNames)
        {
            Myphones.ServerMgmt.ResetMemcachedKeynameRequest inValue = new Myphones.ServerMgmt.ResetMemcachedKeynameRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            inValue.cacheName = cacheName;
            inValue.keyNames = keyNames;
            return ((Myphones.ServerMgmt.MyPhonesServersSoap)(this)).ResetMemcachedKeynameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.GetDBConnInfoResponse> Myphones.ServerMgmt.MyPhonesServersSoap.GetDBConnInfoAsync(Myphones.ServerMgmt.GetDBConnInfoRequest request)
        {
            return base.Channel.GetDBConnInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.ServerMgmt.GetDBConnInfoResponse> GetDBConnInfoAsync(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, int[] softswitchServerIds)
        {
            Myphones.ServerMgmt.GetDBConnInfoRequest inValue = new Myphones.ServerMgmt.GetDBConnInfoRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            inValue.softswitchServerIds = softswitchServerIds;
            return ((Myphones.ServerMgmt.MyPhonesServersSoap)(this)).GetDBConnInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.ResetDBConnsResponse> Myphones.ServerMgmt.MyPhonesServersSoap.ResetDBConnsAsync(Myphones.ServerMgmt.ResetDBConnsRequest request)
        {
            return base.Channel.ResetDBConnsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.ServerMgmt.ResetDBConnsResponse> ResetDBConnsAsync(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, int[] softswitchServerIds)
        {
            Myphones.ServerMgmt.ResetDBConnsRequest inValue = new Myphones.ServerMgmt.ResetDBConnsRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            inValue.softswitchServerIds = softswitchServerIds;
            return ((Myphones.ServerMgmt.MyPhonesServersSoap)(this)).ResetDBConnsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.SetDisplayDBConnInfoResponse> Myphones.ServerMgmt.MyPhonesServersSoap.SetDisplayDBConnInfoAsync(Myphones.ServerMgmt.SetDisplayDBConnInfoRequest request)
        {
            return base.Channel.SetDisplayDBConnInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.ServerMgmt.SetDisplayDBConnInfoResponse> SetDisplayDBConnInfoAsync(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, int[] softswitchServerIds, bool displayOn)
        {
            Myphones.ServerMgmt.SetDisplayDBConnInfoRequest inValue = new Myphones.ServerMgmt.SetDisplayDBConnInfoRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            inValue.softswitchServerIds = softswitchServerIds;
            inValue.displayOn = displayOn;
            return ((Myphones.ServerMgmt.MyPhonesServersSoap)(this)).SetDisplayDBConnInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.SetServerRunnableStateResponse> Myphones.ServerMgmt.MyPhonesServersSoap.SetServerRunnableStateAsync(Myphones.ServerMgmt.SetServerRunnableStateRequest request)
        {
            return base.Channel.SetServerRunnableStateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.ServerMgmt.SetServerRunnableStateResponse> SetServerRunnableStateAsync(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, int[] softswitchServerIds, bool[] states)
        {
            Myphones.ServerMgmt.SetServerRunnableStateRequest inValue = new Myphones.ServerMgmt.SetServerRunnableStateRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            inValue.softswitchServerIds = softswitchServerIds;
            inValue.states = states;
            return ((Myphones.ServerMgmt.MyPhonesServersSoap)(this)).SetServerRunnableStateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.ServerMgmt.SetServerDetailsResponse> Myphones.ServerMgmt.MyPhonesServersSoap.SetServerDetailsAsync(Myphones.ServerMgmt.SetServerDetailsRequest request)
        {
            return base.Channel.SetServerDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.ServerMgmt.SetServerDetailsResponse> SetServerDetailsAsync(Myphones.ServerMgmt.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, int[] softswitchServerIds, int[] runnables, string[] details, int[] weightedLoads, bool reevalRunnable)
        {
            Myphones.ServerMgmt.SetServerDetailsRequest inValue = new Myphones.ServerMgmt.SetServerDetailsRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            inValue.softswitchServerIds = softswitchServerIds;
            inValue.runnables = runnables;
            inValue.details = details;
            inValue.weightedLoads = weightedLoads;
            inValue.reevalRunnable = reevalRunnable;
            return ((Myphones.ServerMgmt.MyPhonesServersSoap)(this)).SetServerDetailsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MyPhonesServersSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.MyPhonesServersSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MyPhonesServersSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/OperationWS/MyphonesServers.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.MyPhonesServersSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/OperationWS/MyphonesServers.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            MyPhonesServersSoap,
            
            MyPhonesServersSoap12,
        }
    }
}
