//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myphones.CallControl
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Myphones.CallControl.MyPhonesCallControlSoap")]
    public interface MyPhonesCallControlSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIfUsageStats", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string[]> GetIfUsageStatsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ping", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> PingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TerminateCallsOlderThan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.CallControl.TerminateCallsOlderThanResponse> TerminateCallsOlderThanAsync(Myphones.CallControl.TerminateCallsOlderThanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelCall", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.CallControl.CancelCallResponse> CancelCallAsync(Myphones.CallControl.CancelCallRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RedirectCall", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.CallControl.RedirectCallResponse> RedirectCallAsync(Myphones.CallControl.RedirectCallRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnswerCall", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.CallControl.AnswerCallResponse> AnswerCallAsync(Myphones.CallControl.AnswerCallRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RejectCall", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.CallControl.RejectCallResponse> RejectCallAsync(Myphones.CallControl.RejectCallRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HoldCall", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.CallControl.HoldCallResponse> HoldCallAsync(Myphones.CallControl.HoldCallRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResumeCall", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.CallControl.ResumeCallResponse> ResumeCallAsync(Myphones.CallControl.ResumeCallRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OriginateCall", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.CallControl.OriginateCallResponse> OriginateCallAsync(Myphones.CallControl.OriginateCallRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OriginateCallAutoAnswer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.CallControl.OriginateCallAutoAnswerResponse> OriginateCallAutoAnswerAsync(Myphones.CallControl.OriginateCallAutoAnswerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TerminateCall", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.CallControl.TerminateCallResponse> TerminateCallAsync(Myphones.CallControl.TerminateCallRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TransferCall", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.CallControl.TransferCallResponse> TransferCallAsync(Myphones.CallControl.TransferCallRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TransferCallAttended", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.CallControl.TransferCallAttendedResponse> TransferCallAttendedAsync(Myphones.CallControl.TransferCallAttendedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ParkCall", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.CallControl.ParkCallResponse> ParkCallAsync(Myphones.CallControl.ParkCallRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PickupParkedCall", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.CallControl.PickupParkedCallResponse> PickupParkedCallAsync(Myphones.CallControl.PickupParkedCallRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ParkCallWithType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.CallControl.ParkCallWithTypeResponse> ParkCallWithTypeAsync(Myphones.CallControl.ParkCallWithTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PickupParkedCallWithType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Myphones.CallControl.PickupParkedCallWithTypeResponse> PickupParkedCallWithTypeAsync(Myphones.CallControl.PickupParkedCallWithTypeRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoteClientInfoHeader
    {
        
        private string ipAddressField;
        
        private string userAgentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ipAddress
        {
            get
            {
                return this.ipAddressField;
            }
            set
            {
                this.ipAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string userAgent
        {
            get
            {
                return this.userAgentField;
            }
            set
            {
                this.userAgentField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TerminateCallsOlderThan", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TerminateCallsOlderThanRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int olderThanMins;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int staleQueuedCallsOlderThanMins;
        
        public TerminateCallsOlderThanRequest()
        {
        }
        
        public TerminateCallsOlderThanRequest(Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, int olderThanMins, int staleQueuedCallsOlderThanMins)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
            this.olderThanMins = olderThanMins;
            this.staleQueuedCallsOlderThanMins = staleQueuedCallsOlderThanMins;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TerminateCallsOlderThanResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TerminateCallsOlderThanResponse
    {
        
        public TerminateCallsOlderThanResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelCall", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CancelCallRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string acctSessionId;
        
        public CancelCallRequest()
        {
        }
        
        public CancelCallRequest(Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string acctSessionId)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
            this.acctSessionId = acctSessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelCallResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CancelCallResponse
    {
        
        public CancelCallResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RedirectCall", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RedirectCallRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string acctSessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string redirectToNumber;
        
        public RedirectCallRequest()
        {
        }
        
        public RedirectCallRequest(Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string acctSessionId, string redirectToNumber)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
            this.acctSessionId = acctSessionId;
            this.redirectToNumber = redirectToNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RedirectCallResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RedirectCallResponse
    {
        
        public RedirectCallResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AnswerCall", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AnswerCallRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string acctSessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string answeringNumber;
        
        public AnswerCallRequest()
        {
        }
        
        public AnswerCallRequest(Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string acctSessionId, string answeringNumber)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
            this.acctSessionId = acctSessionId;
            this.answeringNumber = answeringNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AnswerCallResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AnswerCallResponse
    {
        
        public AnswerCallResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RejectCall", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RejectCallRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string acctSessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string rejectingNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int sipRetCode;
        
        public RejectCallRequest()
        {
        }
        
        public RejectCallRequest(Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string acctSessionId, string rejectingNumber, int sipRetCode)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
            this.acctSessionId = acctSessionId;
            this.rejectingNumber = rejectingNumber;
            this.sipRetCode = sipRetCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RejectCallResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RejectCallResponse
    {
        
        public RejectCallResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HoldCall", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class HoldCallRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string acctSessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string holdingNumber;
        
        public HoldCallRequest()
        {
        }
        
        public HoldCallRequest(Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string acctSessionId, string holdingNumber)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
            this.acctSessionId = acctSessionId;
            this.holdingNumber = holdingNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HoldCallResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class HoldCallResponse
    {
        
        public HoldCallResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResumeCall", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ResumeCallRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string acctSessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string resumingNumber;
        
        public ResumeCallRequest()
        {
        }
        
        public ResumeCallRequest(Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string acctSessionId, string resumingNumber)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
            this.acctSessionId = acctSessionId;
            this.resumingNumber = resumingNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResumeCallResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ResumeCallResponse
    {
        
        public ResumeCallResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OriginateCall", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class OriginateCallRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string callingApplianceNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string calledNumber;
        
        public OriginateCallRequest()
        {
        }
        
        public OriginateCallRequest(Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string callingApplianceNumber, string calledNumber)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
            this.callingApplianceNumber = callingApplianceNumber;
            this.calledNumber = calledNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OriginateCallResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class OriginateCallResponse
    {
        
        public OriginateCallResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OriginateCallAutoAnswer", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class OriginateCallAutoAnswerRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string callingApplianceNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string calledNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int leg1AnswerAfter;
        
        public OriginateCallAutoAnswerRequest()
        {
        }
        
        public OriginateCallAutoAnswerRequest(Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string callingApplianceNumber, string calledNumber, int leg1AnswerAfter)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
            this.callingApplianceNumber = callingApplianceNumber;
            this.calledNumber = calledNumber;
            this.leg1AnswerAfter = leg1AnswerAfter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OriginateCallAutoAnswerResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class OriginateCallAutoAnswerResponse
    {
        
        public OriginateCallAutoAnswerResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TerminateCall", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TerminateCallRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string acctSessionId;
        
        public TerminateCallRequest()
        {
        }
        
        public TerminateCallRequest(Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string acctSessionId)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
            this.acctSessionId = acctSessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TerminateCallResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TerminateCallResponse
    {
        
        public TerminateCallResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TransferCall", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TransferCallRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string acctSessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string targetNumber;
        
        public TransferCallRequest()
        {
        }
        
        public TransferCallRequest(Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string acctSessionId, string targetNumber)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
            this.acctSessionId = acctSessionId;
            this.targetNumber = targetNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TransferCallResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TransferCallResponse
    {
        
        public TransferCallResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TransferCallAttended", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TransferCallAttendedRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string acctSessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string targetNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string replacingDialogId;
        
        public TransferCallAttendedRequest()
        {
        }
        
        public TransferCallAttendedRequest(Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string acctSessionId, string targetNumber, string replacingDialogId)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
            this.acctSessionId = acctSessionId;
            this.targetNumber = targetNumber;
            this.replacingDialogId = replacingDialogId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TransferCallAttendedResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TransferCallAttendedResponse
    {
        
        public TransferCallAttendedResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ParkCall", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ParkCallRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string acctSessionId;
        
        public ParkCallRequest()
        {
        }
        
        public ParkCallRequest(Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string acctSessionId)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
            this.acctSessionId = acctSessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ParkCallResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ParkCallResponse
    {
        
        public ParkCallResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PickupParkedCall", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PickupParkedCallRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string acctSessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string calledNumber;
        
        public PickupParkedCallRequest()
        {
        }
        
        public PickupParkedCallRequest(Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string acctSessionId, string calledNumber)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
            this.acctSessionId = acctSessionId;
            this.calledNumber = calledNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PickupParkedCallResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PickupParkedCallResponse
    {
        
        public PickupParkedCallResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ParkCallWithType", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ParkCallWithTypeRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string acctSessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string parkBayType;
        
        public ParkCallWithTypeRequest()
        {
        }
        
        public ParkCallWithTypeRequest(Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string acctSessionId, string parkBayType)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
            this.acctSessionId = acctSessionId;
            this.parkBayType = parkBayType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ParkCallWithTypeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ParkCallWithTypeResponse
    {
        
        public ParkCallWithTypeResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PickupParkedCallWithType", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PickupParkedCallWithTypeRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string acctSessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string calledNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string parkBayType;
        
        public PickupParkedCallWithTypeRequest()
        {
        }
        
        public PickupParkedCallWithTypeRequest(Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string acctSessionId, string calledNumber, string parkBayType)
        {
            this.RemoteClientInfoHeader = RemoteClientInfoHeader;
            this.sessionToken = sessionToken;
            this.acctSessionId = acctSessionId;
            this.calledNumber = calledNumber;
            this.parkBayType = parkBayType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PickupParkedCallWithTypeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PickupParkedCallWithTypeResponse
    {
        
        public PickupParkedCallWithTypeResponse()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    public interface MyPhonesCallControlSoapChannel : Myphones.CallControl.MyPhonesCallControlSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    public partial class MyPhonesCallControlSoapClient : System.ServiceModel.ClientBase<Myphones.CallControl.MyPhonesCallControlSoap>, Myphones.CallControl.MyPhonesCallControlSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MyPhonesCallControlSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(MyPhonesCallControlSoapClient.GetBindingForEndpoint(endpointConfiguration), MyPhonesCallControlSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MyPhonesCallControlSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MyPhonesCallControlSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MyPhonesCallControlSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MyPhonesCallControlSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MyPhonesCallControlSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string[]> GetIfUsageStatsAsync()
        {
            return base.Channel.GetIfUsageStatsAsync();
        }
        
        public System.Threading.Tasks.Task<string> PingAsync()
        {
            return base.Channel.PingAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.CallControl.TerminateCallsOlderThanResponse> Myphones.CallControl.MyPhonesCallControlSoap.TerminateCallsOlderThanAsync(Myphones.CallControl.TerminateCallsOlderThanRequest request)
        {
            return base.Channel.TerminateCallsOlderThanAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.CallControl.TerminateCallsOlderThanResponse> TerminateCallsOlderThanAsync(Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, int olderThanMins, int staleQueuedCallsOlderThanMins)
        {
            Myphones.CallControl.TerminateCallsOlderThanRequest inValue = new Myphones.CallControl.TerminateCallsOlderThanRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            inValue.olderThanMins = olderThanMins;
            inValue.staleQueuedCallsOlderThanMins = staleQueuedCallsOlderThanMins;
            return ((Myphones.CallControl.MyPhonesCallControlSoap)(this)).TerminateCallsOlderThanAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.CallControl.CancelCallResponse> Myphones.CallControl.MyPhonesCallControlSoap.CancelCallAsync(Myphones.CallControl.CancelCallRequest request)
        {
            return base.Channel.CancelCallAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.CallControl.CancelCallResponse> CancelCallAsync(Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string acctSessionId)
        {
            Myphones.CallControl.CancelCallRequest inValue = new Myphones.CallControl.CancelCallRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            inValue.acctSessionId = acctSessionId;
            return ((Myphones.CallControl.MyPhonesCallControlSoap)(this)).CancelCallAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.CallControl.RedirectCallResponse> Myphones.CallControl.MyPhonesCallControlSoap.RedirectCallAsync(Myphones.CallControl.RedirectCallRequest request)
        {
            return base.Channel.RedirectCallAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.CallControl.RedirectCallResponse> RedirectCallAsync(Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string acctSessionId, string redirectToNumber)
        {
            Myphones.CallControl.RedirectCallRequest inValue = new Myphones.CallControl.RedirectCallRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            inValue.acctSessionId = acctSessionId;
            inValue.redirectToNumber = redirectToNumber;
            return ((Myphones.CallControl.MyPhonesCallControlSoap)(this)).RedirectCallAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.CallControl.AnswerCallResponse> Myphones.CallControl.MyPhonesCallControlSoap.AnswerCallAsync(Myphones.CallControl.AnswerCallRequest request)
        {
            return base.Channel.AnswerCallAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.CallControl.AnswerCallResponse> AnswerCallAsync(Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string acctSessionId, string answeringNumber)
        {
            Myphones.CallControl.AnswerCallRequest inValue = new Myphones.CallControl.AnswerCallRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            inValue.acctSessionId = acctSessionId;
            inValue.answeringNumber = answeringNumber;
            return ((Myphones.CallControl.MyPhonesCallControlSoap)(this)).AnswerCallAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.CallControl.RejectCallResponse> Myphones.CallControl.MyPhonesCallControlSoap.RejectCallAsync(Myphones.CallControl.RejectCallRequest request)
        {
            return base.Channel.RejectCallAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.CallControl.RejectCallResponse> RejectCallAsync(Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string acctSessionId, string rejectingNumber, int sipRetCode)
        {
            Myphones.CallControl.RejectCallRequest inValue = new Myphones.CallControl.RejectCallRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            inValue.acctSessionId = acctSessionId;
            inValue.rejectingNumber = rejectingNumber;
            inValue.sipRetCode = sipRetCode;
            return ((Myphones.CallControl.MyPhonesCallControlSoap)(this)).RejectCallAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.CallControl.HoldCallResponse> Myphones.CallControl.MyPhonesCallControlSoap.HoldCallAsync(Myphones.CallControl.HoldCallRequest request)
        {
            return base.Channel.HoldCallAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.CallControl.HoldCallResponse> HoldCallAsync(Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string acctSessionId, string holdingNumber)
        {
            Myphones.CallControl.HoldCallRequest inValue = new Myphones.CallControl.HoldCallRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            inValue.acctSessionId = acctSessionId;
            inValue.holdingNumber = holdingNumber;
            return ((Myphones.CallControl.MyPhonesCallControlSoap)(this)).HoldCallAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.CallControl.ResumeCallResponse> Myphones.CallControl.MyPhonesCallControlSoap.ResumeCallAsync(Myphones.CallControl.ResumeCallRequest request)
        {
            return base.Channel.ResumeCallAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.CallControl.ResumeCallResponse> ResumeCallAsync(Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string acctSessionId, string resumingNumber)
        {
            Myphones.CallControl.ResumeCallRequest inValue = new Myphones.CallControl.ResumeCallRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            inValue.acctSessionId = acctSessionId;
            inValue.resumingNumber = resumingNumber;
            return ((Myphones.CallControl.MyPhonesCallControlSoap)(this)).ResumeCallAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.CallControl.OriginateCallResponse> Myphones.CallControl.MyPhonesCallControlSoap.OriginateCallAsync(Myphones.CallControl.OriginateCallRequest request)
        {
            return base.Channel.OriginateCallAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.CallControl.OriginateCallResponse> OriginateCallAsync(Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string callingApplianceNumber, string calledNumber)
        {
            Myphones.CallControl.OriginateCallRequest inValue = new Myphones.CallControl.OriginateCallRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            inValue.callingApplianceNumber = callingApplianceNumber;
            inValue.calledNumber = calledNumber;
            return ((Myphones.CallControl.MyPhonesCallControlSoap)(this)).OriginateCallAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.CallControl.OriginateCallAutoAnswerResponse> Myphones.CallControl.MyPhonesCallControlSoap.OriginateCallAutoAnswerAsync(Myphones.CallControl.OriginateCallAutoAnswerRequest request)
        {
            return base.Channel.OriginateCallAutoAnswerAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.CallControl.OriginateCallAutoAnswerResponse> OriginateCallAutoAnswerAsync(Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string callingApplianceNumber, string calledNumber, int leg1AnswerAfter)
        {
            Myphones.CallControl.OriginateCallAutoAnswerRequest inValue = new Myphones.CallControl.OriginateCallAutoAnswerRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            inValue.callingApplianceNumber = callingApplianceNumber;
            inValue.calledNumber = calledNumber;
            inValue.leg1AnswerAfter = leg1AnswerAfter;
            return ((Myphones.CallControl.MyPhonesCallControlSoap)(this)).OriginateCallAutoAnswerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.CallControl.TerminateCallResponse> Myphones.CallControl.MyPhonesCallControlSoap.TerminateCallAsync(Myphones.CallControl.TerminateCallRequest request)
        {
            return base.Channel.TerminateCallAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.CallControl.TerminateCallResponse> TerminateCallAsync(Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string acctSessionId)
        {
            Myphones.CallControl.TerminateCallRequest inValue = new Myphones.CallControl.TerminateCallRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            inValue.acctSessionId = acctSessionId;
            return ((Myphones.CallControl.MyPhonesCallControlSoap)(this)).TerminateCallAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.CallControl.TransferCallResponse> Myphones.CallControl.MyPhonesCallControlSoap.TransferCallAsync(Myphones.CallControl.TransferCallRequest request)
        {
            return base.Channel.TransferCallAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.CallControl.TransferCallResponse> TransferCallAsync(Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string acctSessionId, string targetNumber)
        {
            Myphones.CallControl.TransferCallRequest inValue = new Myphones.CallControl.TransferCallRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            inValue.acctSessionId = acctSessionId;
            inValue.targetNumber = targetNumber;
            return ((Myphones.CallControl.MyPhonesCallControlSoap)(this)).TransferCallAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.CallControl.TransferCallAttendedResponse> Myphones.CallControl.MyPhonesCallControlSoap.TransferCallAttendedAsync(Myphones.CallControl.TransferCallAttendedRequest request)
        {
            return base.Channel.TransferCallAttendedAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.CallControl.TransferCallAttendedResponse> TransferCallAttendedAsync(Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string acctSessionId, string targetNumber, string replacingDialogId)
        {
            Myphones.CallControl.TransferCallAttendedRequest inValue = new Myphones.CallControl.TransferCallAttendedRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            inValue.acctSessionId = acctSessionId;
            inValue.targetNumber = targetNumber;
            inValue.replacingDialogId = replacingDialogId;
            return ((Myphones.CallControl.MyPhonesCallControlSoap)(this)).TransferCallAttendedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.CallControl.ParkCallResponse> Myphones.CallControl.MyPhonesCallControlSoap.ParkCallAsync(Myphones.CallControl.ParkCallRequest request)
        {
            return base.Channel.ParkCallAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.CallControl.ParkCallResponse> ParkCallAsync(Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string acctSessionId)
        {
            Myphones.CallControl.ParkCallRequest inValue = new Myphones.CallControl.ParkCallRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            inValue.acctSessionId = acctSessionId;
            return ((Myphones.CallControl.MyPhonesCallControlSoap)(this)).ParkCallAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.CallControl.PickupParkedCallResponse> Myphones.CallControl.MyPhonesCallControlSoap.PickupParkedCallAsync(Myphones.CallControl.PickupParkedCallRequest request)
        {
            return base.Channel.PickupParkedCallAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.CallControl.PickupParkedCallResponse> PickupParkedCallAsync(Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string acctSessionId, string calledNumber)
        {
            Myphones.CallControl.PickupParkedCallRequest inValue = new Myphones.CallControl.PickupParkedCallRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            inValue.acctSessionId = acctSessionId;
            inValue.calledNumber = calledNumber;
            return ((Myphones.CallControl.MyPhonesCallControlSoap)(this)).PickupParkedCallAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.CallControl.ParkCallWithTypeResponse> Myphones.CallControl.MyPhonesCallControlSoap.ParkCallWithTypeAsync(Myphones.CallControl.ParkCallWithTypeRequest request)
        {
            return base.Channel.ParkCallWithTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.CallControl.ParkCallWithTypeResponse> ParkCallWithTypeAsync(Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string acctSessionId, string parkBayType)
        {
            Myphones.CallControl.ParkCallWithTypeRequest inValue = new Myphones.CallControl.ParkCallWithTypeRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            inValue.acctSessionId = acctSessionId;
            inValue.parkBayType = parkBayType;
            return ((Myphones.CallControl.MyPhonesCallControlSoap)(this)).ParkCallWithTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Myphones.CallControl.PickupParkedCallWithTypeResponse> Myphones.CallControl.MyPhonesCallControlSoap.PickupParkedCallWithTypeAsync(Myphones.CallControl.PickupParkedCallWithTypeRequest request)
        {
            return base.Channel.PickupParkedCallWithTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Myphones.CallControl.PickupParkedCallWithTypeResponse> PickupParkedCallWithTypeAsync(Myphones.CallControl.RemoteClientInfoHeader RemoteClientInfoHeader, string sessionToken, string acctSessionId, string calledNumber, string parkBayType)
        {
            Myphones.CallControl.PickupParkedCallWithTypeRequest inValue = new Myphones.CallControl.PickupParkedCallWithTypeRequest();
            inValue.RemoteClientInfoHeader = RemoteClientInfoHeader;
            inValue.sessionToken = sessionToken;
            inValue.acctSessionId = acctSessionId;
            inValue.calledNumber = calledNumber;
            inValue.parkBayType = parkBayType;
            return ((Myphones.CallControl.MyPhonesCallControlSoap)(this)).PickupParkedCallWithTypeAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MyPhonesCallControlSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.MyPhonesCallControlSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MyPhonesCallControlSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/CallControlWS/MyPhonesCallControl.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.MyPhonesCallControlSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/CallControlWS/MyPhonesCallControl.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            MyPhonesCallControlSoap,
            
            MyPhonesCallControlSoap12,
        }
    }
}
